import { useEffect, useRef, useState } from 'react'; import { createRoot } from 'react-dom/client';
import { KLineChartAdapter } from './charts/KLineChartAdapter'; import type { Timeframe } from './types'; import './style.css';

type Session = { session_id:string; symbol:string; replay_time:number };
const api = async <T,>(path:string, options?:RequestInit):Promise<T> => { const r=await fetch(`/api${path}`, {headers:{'Content-Type':'application/json'},...options}); if(!r.ok) throw new Error(await r.text()); return r.json(); };
function App() {
 const [session,setSession]=useState<Session|null>(null), [timeframe,setTimeframe]=useState<Timeframe>('15m'), [symbol,setSymbol]=useState('BTC'), [status,setStatus]=useState('Ready to begin replay'); const ref=useRef<HTMLDivElement>(null), chart=useRef<KLineChartAdapter>();
 useEffect(()=>{if(!ref.current)return; chart.current=new KLineChartAdapter(ref.current); return()=>chart.current?.destroy()},[]);
 const reload=async(s:Session, tf=timeframe)=>{const rows=await api<Array<Record<string,number>>>(`/sessions/${s.session_id}/candles/${tf}`); chart.current?.setCandles(rows.map(c=>({timestamp:c.open_time,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume}))); setStatus(`${tf} · ${rows.length} visible candles · no future data`)};
 const start=async()=>{const markets=await api<Array<{symbol:string; timeframe:string; start_time:number}>>('/markets'); const item=markets.find(x=>x.symbol===symbol&&x.timeframe==='15m'); if(!item) return setStatus(`No local 15m ${symbol} candles available`); const s=await api<Session>('/sessions',{method:'POST',body:JSON.stringify({symbol,start_time:item.start_time})});setSession(s);await reload(s)};
 const advance=async(count=1)=>{if(!session)return; const s=await api<Session>(`/sessions/${session.session_id}/advance`,{method:'POST',body:JSON.stringify({count})});setSession(s);await reload(s)};
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')advance(e.shiftKey?5:1); if(['1','2','3','4','5'].includes(e.key))setStatus(`Confidence ${e.key} selected`)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)});
 return <main><header><div className="brand">REPLAY <i>01</i></div><div className="live">LOCAL GROUND TRUTH</div><button onClick={start}>START SESSION</button></header><section className="toolbar"><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>BTC</option><option>ETH</option><option>SOL</option></select>{(['4h','1h','15m'] as Timeframe[]).map(tf=><button className={timeframe===tf?'active':''} onClick={()=>{setTimeframe(tf);if(session)reload(session,tf)}}>{tf}</button>)}<span>{session?new Date(session.replay_time).toLocaleString():'Choose a market'}</span><button onClick={()=>advance(1)}>NEXT →</button><button onClick={()=>advance(5)}>+5</button></section><section className="workspace"><div className="chart"><div ref={ref} className="chart-canvas"/><p>{status}</p></div><aside><h2>HUMAN CALL</h2><label>Market state<select><option>NO_STRUCTURE</option><option>VALID_TRIANGLE_NO_TRADE</option><option>MAYBE_SETUP</option><option>TRADE</option></select></label><div className="direction"><button>LONG</button><button>SHORT</button></div><h3>TRADE PLAN</h3>{['ENTRY','STOP LOSS','TAKE PROFIT'].map(x=><label key={x}>{x}<input type="number" placeholder="Price" /></label>)}<button className="commit">PLACE SIMULATED TRADE</button><small>Shortcuts: → next · Shift+→ +5 · 1–5 confidence</small></aside></section></main> }
createRoot(document.getElementById('root')!).render(<App/>);
